ensure created at cannot be overwritten from any updates
ericawright/the-queue pull request #19
Opened 2018-10-18 20:31 UTC by ericawright

2018-10-18 21:21 UTC, bwinton requested changes

2018-10-18 21:21 UTC, bwinton commented on migrations/2018-10-18-144956_updated_at_column_function/up.sql
> +    NEW.created_at := OLD.created_at;
I think it might be better to put this above the `IF`, so that if the only thing that changes is the `created_at`, we don't record a new `updated_at` time…

2018-10-19 15:48 UTC, ericawright commented
updated

2018-10-23 14:45 UTC, bwinton approved these changes
Looks great, thanks!

2018-10-23 14:45 UTC, merged